import { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, Bookmark, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, Circle as CircleHelp, Clock3, Grid2x2X as Grid2X2, Dome as Home, Info, Maximize2, Menu, Monitor, Pause, Play, RotateCcw, Search, SlidersHorizontal, Sparkles, X, Zap } from 'lucide-react';
import rawTopics from './data/event_themes.json';
import { boothConfig } from './data/boothConfig';
import { eventConfig, themes } from './data/eventConfig';
import type { Booth, InnovationTopic, Status, Theme } from './types/innovation';

const themeMeta: Record<Theme, { color:string; short:string; icon:string }> = {
  'Data / Security':{color:'#2b7de9',short:'DATA / SECURITY',icon:'◈'},
  'Emerging Trends':{color:'#7a35e8',short:'EMERGING TRENDS',icon:'✦'},
  'Engineering Efficiency & Enhancements':{color:'#08a66a',short:'ENGINEERING EFFICIENCY',icon:'⚙'},
  'Modernization and Transformation':{color:'#2457b8',short:'MODERNIZATION',icon:'⌁'},
  'Tech 4 Business':{color:'#eb7717',short:'TECH 4 BUSINESS',icon:'✧'},
  'Tech 4 Tech':{color:'#0aa8b6',short:'TECH 4 TECH',icon:'▣'}
};
const statusColor:Record<Status,string> = { YES:'#20b26b', MAYBE:'#e9a21b', WAITLIST:'#8f98a5' };
const normalized = rawTopics.map((item) => {
  const value = item as Record<string, unknown>;
  const text = (key:string, fallback='N/A') => String(value[key] ?? fallback);
  const themeList = text('Themes').split(',').map((t) => t.trim()).filter(Boolean) as Theme[];
  return { id:text('id'), topicName:text('Topic Name'), themes:themeList, category:text('Category'), subCategory:text('Sub Category'), lob:text('LOB'), portfolio:text('Portfolio'), businessOpportunity:text('Business Opportunity / Problem Statement'), innovativeApproach:text('Innovative Approach / Technology'), currentAdoptionStage:text('Current adoption stage'), adoptionScalingNarrative:text('Adoption and scaling narrative'), businessProductivityImpact:text('Business / Productivity Impact'), enterpriseInfluenceRecognition:text('Enterprise Influence & Recognition'), demoPrototype:text('Demo / Prototype'), reusability:text('Reusabilty of the Idea'), whyFeatured:text('Why should this Idea be featured'), spocName:text('SPOC Name Representing the Topic'), status:(['YES','MAYBE','WAITLIST'].includes(text('Status')) ? text('Status') : 'WAITLIST') as Status, score:Number(value.Score) || 0, comments:text('Comments'), additionalNotes:text('Additional Notes') } as InnovationTopic;
});

function App() {
  const [query,setQuery] = useState('');
  const [themeFilter,setThemeFilter] = useState<Theme|'ALL'>('ALL');
  const [statusFilter,setStatusFilter] = useState<Status|'ALL'>('ALL');
  const [scoreFilter,setScoreFilter] = useState('ALL');
  const [activeView,setActiveView] = useState<'hall'|'schedule'|'floorplan'|'shortlist'>('hall');
  const [selectedBooth,setSelectedBooth] = useState<Booth|null>(boothConfig[0]);
  const [selectedTopic,setSelectedTopic] = useState<InnovationTopic|null>(null);
  const [shortlist,setShortlist] = useState<string[]>(() => JSON.parse(localStorage.getItem('innovation-shortlist') || '[]') as string[]);
  const [filterOpen,setFilterOpen] = useState(true);
  const [tour,setTour] = useState(false);
  const [tourIndex,setTourIndex] = useState(0);
  const [intro,setIntro] = useState(true);
  const [boardTick,setBoardTick] = useState(0);
  const [advanced,setAdvanced] = useState({category:'ALL', subCategory:'ALL', lob:'ALL', portfolio:'ALL', adoption:'ALL', boothSize:'ALL'});

  useEffect(() => { const timer=window.setTimeout(()=>setIntro(false),1700); return ()=>window.clearTimeout(timer); },[]);
  useEffect(() => { localStorage.setItem('innovation-shortlist',JSON.stringify(shortlist)); },[shortlist]);
  useEffect(() => { const timer=window.setInterval(()=>setBoardTick((v)=>v+1),4500); return ()=>window.clearInterval(timer); },[]);
  useEffect(() => { if(tour && boothConfig[tourIndex]) setSelectedBooth(boothConfig[tourIndex]); },[tour,tourIndex]);

  const unique = (field:keyof InnovationTopic) => Array.from(new Set(normalized.flatMap((topic) => [String(topic[field])]))).filter(Boolean).sort();
  const filtered = useMemo(() => normalized.filter((topic) => {
    const haystack=[topic.topicName,topic.themes.join(' '),topic.category,topic.subCategory,topic.lob,topic.portfolio,topic.spocName,topic.innovativeApproach,topic.businessOpportunity].join(' ').toLowerCase();
    const scoreOk=scoreFilter==='ALL'||(scoreFilter==='90+'&&topic.score>=90)||(scoreFilter==='80+'&&topic.score>=80)||(scoreFilter==='70+'&&topic.score>=70)||(scoreFilter==='60+'&&topic.score>=60)||(scoreFilter==='BELOW60'&&topic.score<60);
    return (!query||haystack.includes(query.toLowerCase()))&&(themeFilter==='ALL'||topic.themes.includes(themeFilter))&&(statusFilter==='ALL'||topic.status===statusFilter)&&scoreOk&&(advanced.category==='ALL'||topic.category===advanced.category)&&(advanced.subCategory==='ALL'||topic.subCategory===advanced.subCategory)&&(advanced.lob==='ALL'||topic.lob===advanced.lob)&&(advanced.portfolio==='ALL'||topic.portfolio===advanced.portfolio)&&(advanced.adoption==='ALL'||topic.currentAdoptionStage===advanced.adoption);
  }),[query,themeFilter,statusFilter,scoreFilter,advanced]);
  const filteredIds=new Set(filtered.map((t)=>t.id));
  const boothTopics=(booth:Booth) => booth.topicIds.map((id)=>normalized.find((t)=>t.id===id)).filter((t): t is InnovationTopic=>Boolean(t));
  const matchingBooth=(booth:Booth) => boothTopics(booth).some((topic)=>filteredIds.has(topic.id));
  const selectedTopics=selectedBooth?boothTopics(selectedBooth):[];
  const toggleShortlist=(id:string) => setShortlist((items)=>items.includes(id)?items.filter((item)=>item!==id):[...items,id]);
  const clearFilters=()=>{setQuery('');setThemeFilter('ALL');setStatusFilter('ALL');setScoreFilter('ALL');setAdvanced({category:'ALL',subCategory:'ALL',lob:'ALL',portfolio:'ALL',adoption:'ALL',boothSize:'ALL'});};
  const focusBooth=(booth:Booth)=>{setActiveView('hall');setSelectedBooth(booth);setTour(false);};
  const activeBoard=(booth:Booth) => { const topics=boothTopics(booth); return topics.length?topics[boardTick%topics.length]:null; };
  const metrics={yes:normalized.filter((t)=>t.status==='YES').length,maybe:normalized.filter((t)=>t.status==='MAYBE').length,wait:normalized.filter((t)=>t.status==='WAITLIST').length,avg:Math.round(normalized.reduce((a,t)=>a+t.score,0)/normalized.length)};
  const selectClass='select';

  return <div className="app-shell">
    <AnimatePresence>{intro&&<motion.div className="intro" initial={{opacity:1}} exit={{opacity:0}} transition={{duration:.45}}><div className="intro-mark">WELLS<br/>FARGO</div><div className="intro-line"/><div><span>INNOVATION SHOWCASE</span><small>Ideas Today. Impact Tomorrow.</small></div><button onClick={()=>setIntro(false)}>Skip intro</button></motion.div>}</AnimatePresence>
    <header className="topbar"><div className="brand"><div className="wf-mark">WELLS<br/>FARGO</div><div><strong>Innovation Showcase</strong><span>Ideas Today. Impact Tomorrow.</span></div></div><nav><button className={activeView==='hall'?'active':''} onClick={()=>setActiveView('hall')}><Home size={16}/>Home</button><button onClick={()=>{setActiveView('hall');setFilterOpen(true)}}><Sparkles size={16}/>Themes</button><button className={activeView==='shortlist'?'active':''} onClick={()=>setActiveView('shortlist')}><Bookmark size={16}/>My Shortlist <b>{shortlist.length}</b></button><button onClick={()=>setActiveView('schedule')}><CalendarDays size={16}/>Schedule</button></nav><div className="header-search"><Search size={17}/><input aria-label="Search innovations" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search innovations..."/></div><button className="menu-btn" onClick={()=>setFilterOpen(!filterOpen)}><Menu size={20}/></button></header>
    <div className="subbar"><div><span className="live-dot"/> LIVE EXPERIENCE <em>•</em> {eventConfig.eventDurationMinutes/60} hour showcase</div><div className="sub-metrics"><span><b>{normalized.length}</b> Topics</span><span><b>6</b> Themes</span><span><b>9</b> Booths</span><span><b>15</b> Slots</span></div></div>
    <main className="workspace">
      <aside className={`filter-panel ${filterOpen?'open':''}`}><div className="panel-title"><div><small>EXPLORE</small><h3>Navigate the hall</h3></div><button onClick={()=>setFilterOpen(false)}><ChevronLeft size={17}/></button></div><div className="explore-links"><button className={activeView==='hall'?'selected':''} onClick={()=>setActiveView('hall')}><Grid2X2 size={16}/>All booths <span>9</span></button><button className={activeView==='shortlist'?'selected':''} onClick={()=>setActiveView('shortlist')}><Bookmark size={16}/>My shortlist <span>{shortlist.length}</span></button><button className={activeView==='schedule'?'selected':''} onClick={()=>setActiveView('schedule')}><Clock3 size={16}/>Schedule <span>15</span></button></div><div className="filter-section"><label>Filter by theme</label>{themes.map((theme)=><button key={theme} className={`theme-option ${themeFilter===theme?'selected':''}`} onClick={()=>{setThemeFilter(theme);setActiveView('hall')}}><i style={{background:themeMeta[theme].color}}/>{theme}{(theme==='Tech 4 Business'||theme==='Tech 4 Tech')&&<b>GEN AI</b>}</button>)}</div><div className="filter-section"><label>Status</label><div className="status-pills">{(['ALL','YES','MAYBE','WAITLIST'] as const).map((status)=><button key={status} className={statusFilter===status?'selected':''} onClick={()=>setStatusFilter(status)}>{status==='ALL'?'All':status}<i style={{background:status==='ALL'?'#657181':statusColor[status as Status]}}/></button>)}</div></div><div className="filter-section advanced"><button className="advanced-title" onClick={()=>setFilterOpen((v)=>v)}><span><SlidersHorizontal size={15}/>Advanced filters</span><ChevronDown size={15}/></button>{[['category','Category'],['subCategory','Sub category'],['lob','LOB'],['portfolio','Portfolio'],['adoption','Adoption stage']].map(([key,label])=><select key={key} className={selectClass} value={advanced[key as keyof typeof advanced]} onChange={(e)=>setAdvanced({...advanced,[key]:e.target.value})}><option value="ALL">{label}: All</option>{unique(key as keyof InnovationTopic).map((value)=><option key={value} value={value}>{value}</option>)}</select>)}<select className={selectClass} value={scoreFilter} onChange={(e)=>setScoreFilter(e.target.value)}><option value="ALL">Score: All</option><option value="90+">90+</option><option value="80+">80+</option><option value="70+">70+</option><option value="60+">60+</option><option value="BELOW60">Below 60</option></select><button className="clear-link" onClick={clearFilters}>Clear all filters</button></div></aside>
      <section className="stage-area">{activeView==='hall'&&<Hall booths={boothConfig} selected={selectedBooth} onSelect={focusBooth} matching={matchingBooth} activeBoard={activeBoard} filterCount={filtered.length}/>} {activeView==='floorplan'&&<FloorPlan onSelect={focusBooth}/>} {activeView==='schedule'&&<Schedule onSelect={focusBooth}/>} {activeView==='shortlist'&&<Shortlist topics={normalized.filter((t)=>shortlist.includes(t.id))} onOpen={setSelectedTopic} onToggle={toggleShortlist}/>}</section>
      {activeView==='hall'&&<aside className="inspector">{selectedBooth?<><div className="inspector-head"><div><small>BOOTH INSPECTOR</small><h2>{selectedBooth.id}</h2></div><button onClick={()=>setSelectedBooth(null)}><X size={17}/></button></div><div className="inspector-banner" style={{background:themeMeta[(selectedTopics[0]?.themes[0]||'Data / Security') as Theme].color}}><span>{themeMeta[(selectedTopics[0]?.themes[0]||'Data / Security') as Theme].icon}</span><div><b>{themeMeta[(selectedTopics[0]?.themes[0]||'Data / Security') as Theme].short}</b>{selectedTopics[0]?.themes[0].includes('Tech')&&<small>GEN AI</small>}</div></div><div className="inspector-grid"><div><small>BOOTH SIZE</small><b>{selectedBooth.size.replace('x',' × ')}</b></div><div><small>TEAMS</small><b>{selectedBooth.teams}</b></div><div><small>TOPICS</small><b>{selectedTopics.length}</b></div></div><div className="inspector-current"><small>NOW PLAYING ON DISPLAY</small><h3>{activeBoard(selectedBooth)?.topicName}</h3><div className="score-line"><span className="status" style={{color:statusColor[activeBoard(selectedBooth)?.status||'YES']}}>{activeBoard(selectedBooth)?.status}</span><strong>{activeBoard(selectedBooth)?.score}</strong><span>Score</span></div></div><div className="inspector-actions"><button className="primary" onClick={()=>setSelectedTopic(activeBoard(selectedBooth)||selectedTopics[0])}>Explore booth <ArrowRight size={16}/></button><button onClick={()=>setSelectedTopic(selectedTopics[0])}>View all topics <span>{selectedTopics.length}</span></button><button className={selectedTopics.some((t)=>shortlist.includes(t.id))?'bookmarked':''} onClick={()=>selectedTopics[0]&&toggleShortlist(selectedTopics[0].id)}><Bookmark size={16}/> Add to shortlist</button></div></>:<div className="empty-inspector"><div className="empty-icon"><Monitor size={24}/></div><h3>Select a booth to explore</h3><p>Choose any illuminated booth in the hall to inspect its topics, digital board, and presentation teams.</p><div className="tip"><Info size={15}/><span>Tip: use the filters to highlight related booths.</span></div></div>}</aside>}
    </main>
    <div className="bottom-bar"><div className="bottom-view"><button className={activeView==='floorplan'?'active':''} onClick={()=>setActiveView('floorplan')}><Grid2X2 size={17}/>Floor plan</button><button className={activeView==='hall'?'active':''} onClick={()=>setActiveView('hall')}><Monitor size={17}/>Booth view</button><button onClick={()=>{setSelectedBooth(null);setActiveView('hall')}}><RotateCcw size={17}/>Reset view</button></div><div className="tour-controls">{tour?<><button onClick={()=>setTour(false)}><Pause size={15}/>Pause tour</button><button onClick={()=>setTourIndex((i)=>Math.min(8,i+1))}><ArrowRight size={15}/>Next booth</button></>:<button className="tour-btn" onClick={()=>{setTour(true);setTourIndex(0)}}><Play size={15}/>Start guided tour</button>}</div><button className="fullscreen" onClick={()=>document.documentElement.requestFullscreen?.()}><Maximize2 size={17}/>Fullscreen</button></div>
    <AnimatePresence>{selectedBooth&&<motion.div className="topic-drawer" initial={{x:420}} animate={{x:0}} exit={{x:420}}><div className="drawer-top"><div><small>{selectedBooth.id} · {selectedBooth.size.replace('x',' × ')}</small><h2>Topics at this booth</h2></div><button onClick={()=>setSelectedBooth(null)}><X size={19}/></button></div>{selectedTopics.map((topic)=><button className="topic-row" key={topic.id} onClick={()=>setSelectedTopic(topic)}><div className="topic-row-main"><i style={{background:themeMeta[topic.themes[0]].color}}/><span><b>{topic.topicName}</b><small>{topic.category} · {topic.spocName}</small></span></div><div className="topic-meta"><span style={{color:statusColor[topic.status]}}>{topic.status}</span><strong>{topic.score}</strong></div></button>)}</motion.div>}</AnimatePresence>
    <AnimatePresence>{selectedTopic&&<TopicModal topic={selectedTopic} shortlisted={shortlist.includes(selectedTopic.id)} onClose={()=>setSelectedTopic(null)} onToggle={()=>toggleShortlist(selectedTopic.id)}/>}</AnimatePresence>
  </div>
}

function Hall({booths,selected,onSelect,matching,activeBoard,filterCount}:{booths:Booth[];selected:Booth|null;onSelect:(b:Booth)=>void;matching:(b:Booth)=>boolean;activeBoard:(b:Booth)=>InnovationTopic|null;filterCount:number}) { return <div className="hall-wrap"><div className="hall-toolbar"><div><span className="eyebrow">IMMERSIVE EXHIBITION HALL</span><h1>Explore the innovation floor</h1><p>Click a booth to discover the people, ideas, and impact behind the showcase.</p></div><div className="hall-toolbar-right"><span className="match-count"><span className="live-dot"/>{filterCount} topics in view</span><button><CircleHelp size={16}/> How it works</button></div></div><div className="hall-scene"><div className="hall-ceiling"><span/><span/><span/><span/><span/></div><div className="back-wall"><div className="wall-copy"><div className="wall-logo">WELLS<br/>FARGO</div><div><strong>INNOVATION SHOWCASE</strong><span>Ideas Today. Impact Tomorrow.</span></div></div><div className="wall-light left"/><div className="wall-light right"/></div><div className="floor-grid"/><div className="welcome-sign"><span>WELCOME TO THE</span><b>IDEAS FLOOR</b><i>9 booths · 6 themes · 1 shared ambition</i></div><div className="lounge left-lounge"><div className="sofa red"/><div className="sofa gray"/><div className="plant">♧</div></div><div className="lounge right-lounge"><div className="sofa gray"/><div className="sofa red"/><div className="plant">♧</div></div><div className="booth-grid">{booths.map((booth,index)=><BoothCard key={booth.id} booth={booth} index={index} selected={selected?.id===booth.id} dim={!matching(booth)} topic={activeBoard(booth)} onSelect={onSelect}/>)}</div><div className="stage-plinth"><div className="stage-logo">WF</div><span>Innovation in motion</span></div></div><div className="hall-caption"><span><i className="legend-dot match"/>Matching booths glow</span><span><i className="legend-dot"/>Explore the hall by theme, status, or score</span></div></div> }
function BoothCard({booth,index,selected,dim,topic,onSelect}:{booth:Booth;index:number;selected:boolean;dim:boolean;topic:InnovationTopic|null;onSelect:(b:Booth)=>void}) { const theme=(topic?.themes[0]||themes[index%themes.length]) as Theme; return <motion.button className={`booth-card ${booth.size} ${selected?'selected':''} ${dim?'dim':''}`} style={{'--theme':themeMeta[theme].color} as React.CSSProperties} onClick={()=>onSelect(booth)} whileHover={{y:-7}} aria-label={`Open ${booth.id} booth`}><div className="booth-top"><span className="booth-theme"><i>{themeMeta[theme].icon}</i>{themeMeta[theme].short}</span><span className="booth-id">{booth.id}</span></div><div className="booth-structure"><div className="screen"><div className="screen-brand">WF <span>INNOVATION LAB</span></div><small>{themeMeta[theme].short}{theme.includes('Tech')?' · GEN AI':''}</small><b>{topic?.topicName||'Explore innovation'}</b><span className="screen-spoc">{topic?.spocName||'Showcase team'}</span><div className="screen-score"><strong>{topic?.score||'—'}</strong><span>{topic?.status||'LIVE'}</span></div></div><div className="counter"><span>WELLS<br/>FARGO</span></div><div className="plant plant-a">♧</div><div className="plant plant-b">♧</div>{booth.teams===2&&<div className="team-labels"><span>LEFT PRESENTATION</span><span>RIGHT PRESENTATION</span></div>}</div><div className="booth-foot"><span>{booth.size.replace('x',' × ')}</span><span>{booth.teams} {booth.teams===1?'team':'teams'}</span><span className="active-light"/></div></motion.button> }
function FloorPlan({onSelect}:{onSelect:(b:Booth)=>void}) { return <div className="content-view"><div className="view-heading"><div><span className="eyebrow">ORIENTATION</span><h1>Floor plan</h1><p>A clear top-down view of the physical showcase layout.</p></div><div className="dimension-legend"><span><i className="six"/>6 × 6</span><span><i className="eight"/>6 × 8</span></div></div><div className="floor-plan"><div className="plan-stage">INNOVATION SHOWCASE STAGE</div><div className="plan-grid">{boothConfig.map((booth)=><button key={booth.id} className={booth.size} onClick={()=>onSelect(booth)}><span>{booth.id}</span><small>{booth.size.replace('x',' × ')} · {booth.teams} teams</small><i/></button>)}</div><div className="plan-lounge">LOUNGE &amp; CONNECTION</div></div></div> }
function Schedule({onSelect}:{onSelect:(b:Booth)=>void}) { const slots=Array.from({length:15},(_,i)=>{const mins=600+i*20;const hh=Math.floor(mins/60);const mm=String(mins%60).padStart(2,'0');return `${hh}:${mm}`}); return <div className="content-view"><div className="view-heading"><div><span className="eyebrow">LIVE PROGRAMME</span><h1>Presentation schedule</h1><p>15 focused moments across a five-hour innovation experience.</p></div><div className="schedule-date"><CalendarDays size={17}/> Today · 20 min slots</div></div><div className="schedule-list">{slots.map((time,i)=>{const booth=boothConfig[i%boothConfig.length];const topic=normalized[i%normalized.length];return <button key={time} className="schedule-row" onClick={()=>onSelect(booth)}><span className="schedule-time">{time}<small>— {slots[i+1]||'15:00'}</small></span><span className="schedule-booth" style={{borderColor:themeMeta[topic.themes[0]].color}}>{booth.id}<small>{booth.size.replace('x',' × ')}</small></span><span className="schedule-topic"><b>{topic.topicName}</b><small>{topic.spocName} · {topic.themes[0]}</small></span><span className="schedule-status" style={{color:statusColor[topic.status]}}>{topic.status}</span><ArrowRight size={16}/></button>})}</div></div> }
function Shortlist({topics,onOpen,onToggle}:{topics:InnovationTopic[];onOpen:(t:InnovationTopic)=>void;onToggle:(id:string)=>void}) { return <div className="content-view"><div className="view-heading"><div><span className="eyebrow">YOUR COLLECTION</span><h1>My shortlist</h1><p>Ideas you want to return to after the showcase.</p></div><span className="saved-count"><Bookmark size={17}/>{topics.length} saved</span></div>{topics.length?<div className="shortlist-grid">{topics.map((topic)=><button key={topic.id} className="shortlist-card" onClick={()=>onOpen(topic)}><div className="shortlist-card-top"><span style={{background:themeMeta[topic.themes[0]].color}}>{themeMeta[topic.themes[0]].short}</span><button onClick={(e)=>{e.stopPropagation();onToggle(topic.id)}}><Bookmark size={15} fill="currentColor"/></button></div><h3>{topic.topicName}</h3><p>{topic.innovativeApproach}</p><div><span style={{color:statusColor[topic.status]}}>{topic.status}</span><strong>{topic.score}<small> SCORE</small></strong></div></button>)}</div>:<div className="empty-state"><Bookmark size={25}/><h3>Your shortlist is waiting</h3><p>Save topics from any booth to create your own collection of ideas.</p></div>}</div> }
function TopicModal({topic,shortlisted,onClose,onToggle}:{topic:InnovationTopic;shortlisted:boolean;onClose:()=>void;onToggle:()=>void}) { const sections=[['BUSINESS OPPORTUNITY',topic.businessOpportunity],['INNOVATIVE APPROACH',topic.innovativeApproach],['ADOPTION',`${topic.currentAdoptionStage} — ${topic.adoptionScalingNarrative}`],['IMPACT',`${topic.businessProductivityImpact} ${topic.enterpriseInfluenceRecognition}`],['REUSABILITY',topic.reusability],['DEMO',topic.demoPrototype],['WHY THIS IDEA',topic.whyFeatured],['OWNERSHIP',topic.spocName],['EVALUATION',`${topic.status} · Score ${topic.score}. ${topic.comments} ${topic.additionalNotes}`]];return <motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="topic-modal" initial={{y:40,opacity:0}} animate={{y:0,opacity:1}} exit={{y:40,opacity:0}}><div className="modal-header"><div><span className="modal-kicker" style={{color:themeMeta[topic.themes[0]].color}}>{themeMeta[topic.themes[0]].short}{topic.themes[0].includes('Tech')&&' · GEN AI'}</span><h2>{topic.topicName}</h2><div className="modal-tags"><span>{topic.category}</span><span>{topic.subCategory}</span><span>{topic.lob}</span><span>{topic.portfolio}</span></div></div><div className="modal-actions"><button className={shortlisted?'bookmarked':''} onClick={onToggle}><Bookmark size={17} fill={shortlisted?'currentColor':'none'}/>{shortlisted?'Saved':'Save idea'}</button><button onClick={onClose}><X size={20}/></button></div></div><div className="modal-summary"><div><small>STATUS</small><b style={{color:statusColor[topic.status]}}>{topic.status}</b></div><div><small>SCORE</small><b>{topic.score}<span>/100</span></b></div><div><small>SPOC</small><b>{topic.spocName}</b></div></div><div className="modal-sections">{sections.map(([title,body])=><section key={title}><span>{title}</span><p>{body}</p></section>)}</div></motion.div></motion.div> }
export default App;
